spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: false

  # use this when using multiple spring main classes in same project
#  main.allow-bean-definition-overriding: true

# setup logging for transaction
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: ERROR
    org.springframework.transaction: TRACE
    org.hibernate: ERROR
    com.sda.spring.data.jpa: INFO
